name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  go_router: ^8.0.1
  objectbox: ^2.0.0
  dio: ^5.2.0+1
  provider: ^6.0.5
  equatable: ^2.0.5
  objectbox_sync_flutter_libs: ^2.1.0
  path_provider: ^2.0.15
  simple_logger: ^1.9.0+2
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  objectbox_generator: any

flutter:
  uses-material-design: true
